import type {
  ClassSession,
  Subject,
  SubjectGroup,
  SubjectGroupDetail,
} from '@/lib/types';

const TEXT_NODE = 3;
const ELEMENT_NODE = 1;

/**
 * Visible text of an element, with JSF's generous whitespace collapsed.
 *
 * Plain `textContent` is not usable here: JSF inlines a `<script>` block into
 * the first result cell and a `<style>` block into the category cell, so the
 * subject code would come back with a few hundred characters of JavaScript
 * attached.
 */
export function text(el: Element | null | undefined): string {
  if (!el) return '';
  let out = '';
  const walk = (node: Node) => {
    if (node.nodeType === TEXT_NODE) {
      out += node.nodeValue ?? '';
      return;
    }
    if (node.nodeType !== ELEMENT_NODE) return;
    const tag = (node as Element).tagName;
    if (tag === 'SCRIPT' || tag === 'STYLE') return;
    node.childNodes.forEach(walk);
  };
  walk(el);
  return out.replace(/\s+/g, ' ').trim();
}

/**
 * Maps a RichFaces table's header labels to column indices.
 *
 * The `id` attributes on these tables (`j_id19`, `j_id111`, …) are generated by
 * JSF and shift whenever the page is edited, so every parser here keys off the
 * header text instead.
 */
export function headerIndex(table: HTMLTableElement): Map<string, number> {
  const map = new Map<string, number>();
  const headerRow = table.querySelector('thead tr');
  if (!headerRow) return map;
  headerRow.querySelectorAll('th').forEach((th, i) => {
    const label = text(th);
    if (label) map.set(label, i);
  });
  return map;
}

/** Finds the first table in `root` whose header row contains every label. */
export function findTableByHeaders(
  root: ParentNode,
  labels: string[],
): HTMLTableElement | null {
  const tables = root.querySelectorAll<HTMLTableElement>('table');
  for (const table of tables) {
    const headers = headerIndex(table);
    if (labels.every((l) => headers.has(l))) return table;
  }
  return null;
}

const EXPORT_HEADERS = {
  code: 'Subject Code',
  title: 'Subject Title',
  group: 'Subject Group Code',
  component: 'Component Code',
  every: 'For Every (Week)',
  startWeek: 'Start Week',
  endWeek: 'End Week',
  day: 'Day of Week',
  startTime: 'Start Time',
  endTime: 'End Time',
  venue: 'Venue',
  staff: 'Teaching Staff',
  remark: 'Remark',
} as const;

/**
 * Splits the "Subject Group Code" cell.
 *
 * When several groups share one class, PolyU lists them together in a single
 * row — `1015, 125, 175`. Treating that string as one group would invent a
 * group that does not exist while leaving the three real ones without their
 * shared lecture, so each code gets its own copy of the session.
 */
function splitGroupCodes(cell: string): string[] {
  const codes = cell
    .split(',')
    .map((c) => c.trim())
    .filter(Boolean);
  return codes.length > 0 ? codes : [cell.trim()];
}

/**
 * Parses `subject-search-export-timetable.jsf`, which returns the full timetable
 * for *every* subject in the current search — all pages at once, in one request.
 * That is the whole reason we can expand a result row without a round trip.
 *
 * Returns subject code → groups, sorted by group code.
 */
export function parseExportTimetable(html: string): Map<string, SubjectGroup[]> {
  const doc = new DOMParser().parseFromString(html, 'text/html');
  const table = findTableByHeaders(doc, [
    EXPORT_HEADERS.code,
    EXPORT_HEADERS.group,
    EXPORT_HEADERS.staff,
  ]);
  const result = new Map<string, SubjectGroup[]>();
  if (!table) return result;

  const cols = headerIndex(table);
  const col = (row: HTMLTableRowElement, label: string): string => {
    const i = cols.get(label);
    return i === undefined ? '' : text(row.cells[i]);
  };

  for (const row of table.querySelectorAll<HTMLTableRowElement>('tbody tr')) {
    const subjectCode = col(row, EXPORT_HEADERS.code);
    const groupCode = col(row, EXPORT_HEADERS.group);
    if (!subjectCode) continue;

    const session: ClassSession = {
      componentCode: col(row, EXPORT_HEADERS.component),
      everyWeeks: Number(col(row, EXPORT_HEADERS.every)) || 1,
      startWeek: Number(col(row, EXPORT_HEADERS.startWeek)) || 0,
      endWeek: Number(col(row, EXPORT_HEADERS.endWeek)) || 0,
      dayOfWeek: col(row, EXPORT_HEADERS.day),
      startTime: col(row, EXPORT_HEADERS.startTime),
      endTime: col(row, EXPORT_HEADERS.endTime),
      venue: col(row, EXPORT_HEADERS.venue),
      teachingStaff: col(row, EXPORT_HEADERS.staff),
      remark: col(row, EXPORT_HEADERS.remark),
    };

    const groups = result.get(subjectCode) ?? [];
    for (const code of splitGroupCodes(groupCode)) {
      let group = groups.find((g) => g.groupCode === code);
      if (!group) {
        group = { groupCode: code, sessions: [] };
        groups.push(group);
      }
      group.sessions.push(session);
    }
    result.set(subjectCode, groups);
  }

  for (const groups of result.values()) {
    // Group codes are numeric strings of differing length (`125` and `1011`),
    // so plain lexicographic order would put `1011` before `125`.
    groups.sort((a, b) =>
      a.groupCode.localeCompare(b.groupCode, undefined, { numeric: true }),
    );
  }
  return result;
}

const GROUP_DETAIL_HEADERS = {
  group: 'Subject Group',
  programmes:
    'Students of these programmes are eligible for taking this subject group',
  type: 'Group Type',
  size: 'Group Size',
  vacancies: 'Vacancies*',
  waitlist: 'Waitlist available if no vacancy',
} as const;

/**
 * Reads the vacancies cell, which the page prints in one of two shapes:
 * a plain `(25)`, or `(W=40)/(Top-up vac=0)` once students are queueing. The
 * second shape means the group is full, so it yields no seats.
 */
function parseVacancies(cell: string): Pick<
  SubjectGroupDetail,
  'seats' | 'waiting' | 'topUp'
> {
  const waiting = cell.match(/W\s*=\s*(\d+)/i);
  const topUp = cell.match(/Top-up\s*vac\s*=\s*(\d+)/i);
  // Only a bare count is a seat count — the waitlist form is full of digits too.
  const plain = cell.trim().match(/^\((\d+)\)$|^(\d+)$/);
  return {
    seats: plain ? Number(plain[1] ?? plain[2]) : waiting ? 0 : null,
    waiting: waiting ? Number(waiting[1]) : null,
    topUp: topUp ? Number(topUp[1]) : null,
  };
}

/**
 * Parses the "Subject Group Details" table of `subject-search-details.jsf`.
 *
 * Returns group code → detail. The group codes match the timetable export's, so
 * the two sources merge on that key.
 */
export function parseGroupDetails(
  html: string,
): Map<string, SubjectGroupDetail> {
  const doc = new DOMParser().parseFromString(html, 'text/html');
  const table =
    doc.querySelector<HTMLTableElement>('table[id$=":groupTable"]') ??
    findTableByHeaders(doc, [
      GROUP_DETAIL_HEADERS.group,
      GROUP_DETAIL_HEADERS.type,
      GROUP_DETAIL_HEADERS.vacancies,
    ]);
  const result = new Map<string, SubjectGroupDetail>();
  if (!table) return result;

  const cols = headerIndex(table);
  const cellAt = (
    row: HTMLTableRowElement,
    label: string,
  ): HTMLTableCellElement | undefined => {
    const i = cols.get(label);
    return i === undefined ? undefined : row.cells[i];
  };

  for (const row of table.querySelectorAll<HTMLTableRowElement>('tbody tr')) {
    const groupCode = text(cellAt(row, GROUP_DETAIL_HEADERS.group));
    if (!groupCode) continue;

    // Each eligible programme is its own span; their text runs together
    // otherwise, turning `62401-` + `62401-DSA` into one unreadable code.
    const programmeCell = cellAt(row, GROUP_DETAIL_HEADERS.programmes);
    const spans = programmeCell?.querySelectorAll('.fixed-size-label');
    const eligibleProgrammes = spans?.length
      ? Array.from(spans, text).filter(Boolean)
      : [text(programmeCell)].filter(Boolean);

    const vacancies = text(cellAt(row, GROUP_DETAIL_HEADERS.vacancies));
    result.set(groupCode, {
      eligibleProgrammes,
      groupType: text(cellAt(row, GROUP_DETAIL_HEADERS.type)),
      groupSize: text(cellAt(row, GROUP_DETAIL_HEADERS.size)),
      vacancies,
      ...parseVacancies(vacancies),
      waitlistAvailable: text(cellAt(row, GROUP_DETAIL_HEADERS.waitlist)),
    });
  }
  return result;
}

const SEARCH_HEADERS = {
  code: 'Subject Code',
  title: 'Subject Title',
  department: 'Subject Offering Department',
  category: 'Category',
  level: 'Subject Level',
  credits: 'Credit(s)',
} as const;

/** The subject search result table currently rendered on the page. */
export function findSearchTable(
  root: ParentNode = document,
): HTMLTableElement | null {
  const byId = root.querySelector<HTMLTableElement>(
    'table[id$=":searchTable"]',
  );
  if (byId) return byId;
  return findTableByHeaders(root, [SEARCH_HEADERS.code, SEARCH_HEADERS.title]);
}

/** Reads one result row into a {@link Subject}; `groups` is filled in later. */
export function parseSearchRow(
  row: HTMLTableRowElement,
  cols: Map<string, number>,
): Subject | null {
  const col = (label: string): string => {
    const i = cols.get(label);
    return i === undefined ? '' : text(row.cells[i]);
  };
  const subjectCode = col(SEARCH_HEADERS.code);
  if (!subjectCode) return null;

  const categoryIndex = cols.get(SEARCH_HEADERS.category);
  const categoryCell =
    categoryIndex === undefined ? undefined : row.cells[categoryIndex];
  const categories = categoryCell
    ? Array.from(categoryCell.querySelectorAll('li'), text).filter(Boolean)
    : [];

  return {
    subjectCode,
    subjectTitle: col(SEARCH_HEADERS.title),
    offeringDepartment: col(SEARCH_HEADERS.department),
    categories: categories.length ? categories : [text(categoryCell)].filter(Boolean),
    level: col(SEARCH_HEADERS.level),
    credits: col(SEARCH_HEADERS.credits),
    groups: [],
  };
}

export { SEARCH_HEADERS };
